FROM mcr.microsoft.com/playwright:v1.40.1-focal

WORKDIR /testfolder

LABEL version = "1.0.0"
LABEL owner = "Acuity Mojito QE Team"
LABEL description = "Minimal container for running playwright"

RUN npm install -g npm@10.2.5

RUN adduser --system --group testrunner
RUN chown -R testrunner:testrunner /testfolder

USER testrunner

ENTRYPOINT ["npx", "playwright", "test"]