apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: playwright-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: playwright-container
              image: playwright-automation:latest
