kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: playwright-app
  namespace: k8s-playwright
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: playwright-container
              image: playwright-automation:latest
